feat(calculate-shipping): free shipping option by product (#9)
ecomplus/app-custom-shipping pull request #10
Opened 2023-03-01 03:49 UTC by matheusgnreis

2023-03-01 04:02 UTC, leomp12 requested changes

2023-03-01 04:02 UTC, leomp12 commented on assets/application.json
> +              "title": "Lista de produtos para frete grátis",
```suggestion
              "title": "Produtos com frete grátis",
```

2023-03-01 04:02 UTC, leomp12 commented on assets/application.json
> +              "description": "Se preenchido, será dado frete grátis",
```suggestion
              "description": "Será aplicado frete grátis se algum dos produtos especificados estiver no carrinho",
```

2023-03-01 04:02 UTC, leomp12 commented on routes/ecom/modules/calculate-shipping.js
> +            const hasProduct = params.items.some(item => rule.product_ids.indexOf(item.product_id) > -1)
Mas não deveria aplicar frete grátis só se todos os produtos estiverem configurados para tal? 🤔

2023-03-01 04:02 UTC, leomp12 commented on routes/ecom/modules/calculate-shipping.js
> +            const hasProduct = params.items.some(item => rule.product_ids.indexOf(item.product_id) > -1)
Quer dizer, se uma lista de produtos está em BH e um outro produto está na Argentina, se o cliente comprar só produtos que estão em BH você deve querer aplicar a regra, mas se o cliente comprar o produto da Argentina, mesmo que junto dos outros produtos de BH, você não deve querer aplicar a regra.

2023-03-01 04:02 UTC, leomp12 commented on routes/ecom/modules/calculate-shipping.js
> +            const hasProduct = params.items.some(item => rule.product_ids.indexOf(item.product_id) > -1)
Esse raciocínio vale pra dropshipping

2023-03-01 04:02 UTC, leomp12 commented on assets/application.json
> +              "description": "Se preenchido, será dado frete grátis",
Por quê esse mock em _frete grátis_ inclusive?
Esse filtro por produtos não deveria ser só um filtro adicional de regra? Que poderia ser uma regra de frete grátis ou uma regra de frete fixo...

2023-03-01 11:08 UTC, matheusgnreis commented on routes/ecom/modules/calculate-shipping.js
> +            const hasProduct = params.items.some(item => rule.product_ids.indexOf(item.product_id) > -1)
Posso colocar uma configuração opcional para isso. Quem pediu, era se tivesse qualquer item.

2023-03-01 11:11 UTC, matheusgnreis commented on routes/ecom/modules/calculate-shipping.js
> +            const hasProduct = params.items.some(item => rule.product_ids.indexOf(item.product_id) > -1)
Outros clientes já tinham solicitado isso pra correios nesse tipo de configuração, tendo qualquer um manter frete grátis. Então comecei por esse pra depois ir pra outros

2023-03-01 11:14 UTC, matheusgnreis commented on assets/application.json
> +              "description": "Se preenchido, será dado frete grátis",
Não entendi como seria pra frete fixo. Porque o valor do frete já é fixo, ou você fala não dar acréscimo por peso ou algo mais, se tiver alguns produtos no carrinho

2023-03-01 18:12 UTC, leomp12 commented on assets/application.json
> +              "description": "Se preenchido, será dado frete grátis",
O valor do frete é o valor da regra.
Ele pode criar uma regra por 20 reais sem filtro por produto e outra regra por 10 reais com filtro por produto.
ID do produto nesse caso é só um filtro a mais, assim como seria filtro por peso...

2023-03-01 18:13 UTC, leomp12 commented on routes/ecom/modules/calculate-shipping.js
> +            const hasProduct = params.items.some(item => rule.product_ids.indexOf(item.product_id) > -1)
Bem estranho, mas então tá...

2023-03-01 18:14 UTC, leomp12 commented on assets/application.json
> +              "description": "Se preenchido, será dado frete grátis",
E a regra pode ser de frete grátis ou pode ser de um frete fixo mais barato, assim como se pode criar duas regras por peso, uma segunda, com menor peso poderia ser grátis ou mais barata...

2023-03-01 18:18 UTC, matheusgnreis commented on assets/application.json
> +              "description": "Se preenchido, será dado frete grátis",
No caso, faz mais sentido colocar dentro de services né. Porque assim seria para a forma de envio e não para uma regra qualquer, no caso, independente da regra de envio, se for a forma de envio x e tiver os produtos no carrinho, deve ter frete grátis..

2023-03-02 17:25 UTC, leomp12 commented on routes/ecom/modules/calculate-shipping.js
> +      shippingRules = newShippingRules
Isso tudo era vontade de experimentar métodos "diferentes" de array prototype? 😄 

```suggestion
      shippingRules.forEach(rule => {
        const service = services.find(service => service.service_code === rule.service_code)
        if (service) {
          rule.free_shipping_all = service.free_shipping_all
          rule.product_ids = service.product_ids
        }
      })
```

2023-03-02 17:25 UTC, leomp12 commented on assets/application.json
> +            },
Você não tá tratando isso aqui

2023-03-02 17:25 UTC, leomp12 commented on assets/application.json
> +              "description": "Se preenchido, será dado frete grátis",
Não acho não viu, acho que é da regra mesmo isso aí

2023-03-02 17:28 UTC, leomp12 commented on assets/application.json
> +              "description": "Se preenchido, será dado frete grátis",
Não consigo enxergar uma cenário que o cara coloca frete grátis em várias regras pra um serviço, definitivamente não me parece uma config comum, e portanto não deveria estar no admin settings.
Na rule pode até ser, mas ainda não acho que deveria forçar frete grátis, simplesmente usa o valor de frete da regra, que pode ser grátis ou não, depende...

2023-03-02 17:33 UTC, leomp12 commented on assets/application.json
> +              "description": "Se preenchido, será dado frete grátis",
O `product_ids` na prática não mexe no valor da regra (não força frete grátis), ele só é um filtro da regra.
Se o lojista quer aplicar frete grátis sempre que um produto estiver no carrinho basta que ele crie uma regra pro serviço em específico, com o(s) produto especificado, sem filtro por peso e pra todo o range de CEP, com frete grátis. Essa regra, pelo valor mais baixo, vai sobressair às outras.

2023-03-02 17:34 UTC, leomp12 commented on assets/application.json
> +              "description": "Se preenchido, será dado frete grátis",
Da mesma forma que ele faria pra aplicar frete grátis sempre pra um serviço específico pra pesos até 1kg por exemplo.

2023-03-02 20:22 UTC, matheusgnreis commented on assets/application.json
> +              "description": "Se preenchido, será dado frete grátis",
O cliente pode colocar frete grátis para um valor mínimo e/ou produtos no carrinho. Que é justamente a proposição dos clientes que pedem. Por exemplo, se o cara comprar acima de 200 reais, vai ter frete grátis no PAC. Em determinadas promoções, quer incentivar a compra de determinado produto dando frete grátis. A loja pode criar outra regra, mas se tiver muitas regras, exemplo a jessimake tem 10 transportadoras, criar a regra opcional e depois procurar para remover pode ser um problema.
Mas posso mudar pra regra também, no caso muda a forma de implementação pelo que entendi, ao invez de forçar frete grátis no final

2023-03-02 20:23 UTC, matheusgnreis commented on assets/application.json
> +            },
Está no outro deploy, vou mudar novamente.

2023-03-02 23:27 UTC, leomp12 commented on assets/application.json
> +              "description": "Se preenchido, será dado frete grátis",
Pra esse frete grátis é uma regra a mais apenas, nesse caso aí de 10 transportadoras vai ficar complicado independente disso, afinal o app não foi feito exatamente pra cobrir esses casos.

Não faz sentido isso estar nos serviços, aliás o objeto `services` separado foi exatamente tentando simplificar o cenário mais simples pra cadastro apenas da forma de envio, sem regras, aí vai ter lá "Rótulo", "Transportadora", "Código do serviço", e do nada _"IDs de produtos para aplicar frete grátis"_...
Você quer atrapalhar o mais básico pra cobrir um caso incomum, se fosse assim era menos mal jogar no objeto serviço um _"Peso máximo para frete grátis"_ que é um caso bem mais comum, ou _"CEP para frete grátis"_.

2023-03-03 01:00 UTC, leomp12 commented on assets/application.json
> +              "items": {
Sabe que os títulos/descrições aqui não fazem sentido né?
Essa parte do _frete grátis_ ...

2023-03-03 01:00 UTC, leomp12 commented on assets/application.json
> +              "items": {
Na verdade deve ser algo parecido com https://github.com/ecomplus/discounts/blob/master/assets/application.json#L383-L384 , só que aqui é produtos

2023-03-03 01:00 UTC, leomp12 commented on assets/application.json
> +              "items": {
A ordem dos campos também é melhor invertida, primeiro o usuário define se vai selecionar produtos, depois ele decide se tem que bater todos eles ou apenas um da lista (antes de ele visualizar a opção de produtos o checkbox não vai fazer sentido: "todos os itens da lista", que lista? 🙃 )

2023-03-03 01:00 UTC, leomp12 commented on assets/application.json
> +            "free_shipping_all": {
```suggestion
            "all_product_ids": {
```

2023-03-03 15:58 UTC, leomp12 requested changes
Os títulos e descrições dos campos seguem incoerentes mesmo depois do seu último commit...

2023-03-03 15:58 UTC, leomp12 commented on assets/application.json
>                "description": "Será aplicado frete grátis se algum dos produtos especificados estiver no carrinho",
https://github.com/ecomplus/app-custom-shipping/pull/10#discussion_r1123927186
https://github.com/ecomplus/app-custom-shipping/pull/10#discussion_r1123927275

2023-03-03 15:58 UTC, leomp12 commented on assets/application.json
>                "description": "Será aplicado frete grátis se algum dos produtos especificados estiver no carrinho",
De novo, não tem essa de frete grátis aqui.
Na config da regra tem um field pra valor, se ele for 0 o frete é grátis, se não ele não é grátis, sem ambiguidade.

2023-03-03 15:58 UTC, leomp12 commented on assets/application.json
>                "description": "Será aplicado frete grátis se algum dos produtos especificados estiver no carrinho",
Da mesma forma por exemplo em regras de desconto, não é _Lista de clientes para 100% de desconto_, é _Lista de clientes selecionados_ , o valor do desconto é outro campo da regra

2023-03-07 22:57 UTC, leomp12 requested changes

2023-03-07 22:57 UTC, leomp12 commented on assets/application.json
> +              "description": "Se preenchido, será dado frete grátis se houver um dos itens no carrinho",
😆 
vamos lá novamente https://github.com/ecomplus/app-custom-shipping/pull/10#pullrequestreview-1324141197

2023-03-07 23:07 UTC, leomp12 commented on assets/application.json
> +              "description": "Se preenchido, será dado frete grátis se houver um dos itens no carrinho",
> não vou deixar sugestão de alteração porque se não você só aceita sem mal mal ler, mas segue o mesmo problema nas descrições dos campos 🙃

2023-03-08 02:03 UTC, matheusgnreis commented on assets/application.json
> +              "description": "Se preenchido, será dado frete grátis se houver um dos itens no carrinho",
Mano, eu fiz igual a descrição do app. Eu preciso falar sobre o que é essa lista, porque é direcionada 100% a frete grátis, mesmo que não seja ela quem vai dar, pois a pessoa além de colocar os produtos, precisa configurar frete grátis na regra, vou mudar de novo e você vê

2023-03-08 02:12 UTC, matheusgnreis commented on assets/application.json
> +              "description": "Se preenchido, será dado frete grátis se houver um dos itens no carrinho",
Pronto, agora eu acho que deixei da forma que deseja, porque pode ser pra frete grátis, ou pra um preço especifico..

2023-03-08 19:18 UTC, leomp12 commented on assets/application.json
> +              "description": "Se ativo, será aplicado a condição configurada apenas para a lista de produtos no carrinho",
melhorou bem, mas acho que dá pra ficar mais claro especialmente o segundo campo.

```suggestion
              "description": "Se preenchido, a regra de envio estará disponível apenas se pelo menos um dos itens estiver no carrinho",
              "type": "array",
              "items": {
                "type": "string",
                "pattern": "^[a-f0-9]{24}$",
                "title": "ID do produto"
              }
            },
            "all_product_ids": {
              "type": "boolean",
              "title": "Checar todos os produtos",
              "description": "Se ativo, a regra será disponibilizada apenas se todos os produtos selecionados estiverem no carrinho",
```

2023-03-08 19:20 UTC, leomp12 commented on assets/application.json
> +              "description": "Se ativo, a regra será disponibilizada apenas se todos os produtos selecionados estiverem no carrinho",
```suggestion
              "description": "Se ativo, a regra será disponibilizada somente se todos os itens do carrinho estiverem na lista de produtos selecionados",
```

2023-03-08 19:21 UTC, leomp12 commented on assets/application.json
> +              "description": "Se preenchido, a regra de envio estará disponível apenas se pelo menos um dos itens estiver no carrinho",
```suggestion
              "description": "Se preenchido, a regra de envio estará disponível apenas se pelo menos um destes produtos estiver no carrinho",
```

2023-03-08 19:22 UTC, leomp12 approved these changes

2023-03-08 19:22 UTC, merged