chore(application) : add delivery instructions at config
ecomplus/app-custom-shipping pull request #8
Opened 2022-07-04 17:17 UTC by matheusgnreis

Sometimes, when config the first form with delivery instructions, we cant just edit it, so its better to insert this config at shipping rules

2022-07-04 20:14 UTC, leomp12 requested changes
Na verdade não tinha `delivery_instructions` no schema da regra de envio pra não ir deixando essa config cada vez maior. O mesmo acontece com outros fields que são configurados em formas de envio específicas definidas no componente de edição desse app https://github.com/ecomplus/admin-marketplace/blob/master/src/views/apps/AppCustomShipping.vue

Ou seja, não é porque foi esquecido, juntar todos os campos na configuração da regra "genérica" deixaria essa configuração cada vez mais complexa.

É recorrente a necessidade disso? Não é pior pra maioria deixar isso por padrão?

> Algo parecido tem que ser feito no app de descontos inclusive, pra reduzir alguns campos que da configuração genérica e adicionar formulários separados presetados para cenários comuns...

2022-07-04 20:14 UTC, leomp12 commented on assets/application.json
> +              "type": "text",
`type: 'text'` não existe 🙃 
https://json-schema.org/understanding-json-schema/reference/type.html

2022-07-04 20:23 UTC, matheusgnreis commented on assets/application.json
> +              "type": "text",
KKKKKKKKKKKKKKKKKKKKKKK, puta merda, onde estive com a cabeça, tô doido só pode

2022-07-04 20:26 UTC, matheusgnreis commented
> É recorrente a necessidade disso? Não é pior pra maioria deixar isso por padrão?

Recorrentemente dá esse erro, quando alguem sem querer cria uma nova regra com o mesmo service code, ai eu modifico no app. Mas por exemplo, se alguem quer colocar varias retiradas, faz isso uma vez só, porque não consegue editar mais por exemplo. Parece que é um bug, mostra lá renderizado, mas não consegue editar. Acho que esse campo a mais, não fará diferença

2022-07-05 00:30 UTC, leomp12 commented on assets/application.json
> +              "description": "Insira informações detalhadas para seu cliente retirar o pedido"
```suggestion
              "description": "Insira informações adicionais para retirada ou entrega do pedido"
```

Não necessariamente é retirada aqui...

2022-07-05 00:30 UTC, leomp12 approved these changes

2022-07-05 00:31 UTC, merged